### ISSUE TITLE
画面と機能

### ISSUE THREAD

**Issue by mogulla3** [mogulla3/darktree#68]
## 機能
- デッキの作成ができる（GET /decks/new → POST /decks）
- デッキの編集ができる（GET /decks/:id/edit → PUT /decks/:id）
- デッキの削除ができる（DELETE /decks/:id）
- デッキに属するカードを選択できる（?）
- デッキに属するカードを同時に複数作成することができる（?）
- デッキに属するカードを同時に複数登録することができる（登録 = 既に存在するカードを選択したデッキ配下に登録する）
- デッキに属するカードを同時に複数削除することができる
- デッキに属するカードを一覧で閲覧できる（メイン機能）
- カードの作成ができる（GET /cards/new → POST /cards/:id）
- カードのインポートができる（GET /cards/new → POST /cards/import）
- カードの編集ができる（GET /cards/:id/edit → PUT /cards/:id）
- カードの削除ができる（DELETE /cards/:id）
- カードの学習状況を登録できる
- カードをお気に入りに登録することができる

## 画面と機能のマッピング
- デッキ一覧画面（）
  - [ ] デッキの作成ができる 
  - [ ] デッキの編集ができる
  - [ ] デッキの削除ができる
- 選択したデッキ配下のカード一覧画面
  - [ ] デッキに属するカードを一覧で閲覧できる
  - [ ] カードの学習状況を登録できる
  - [ ] カードをお気に入りに登録することができる
- カード作成画面
  - [x] カードの作成ができる
  - [x] カードのインポートができる
- カード詳細画面
  - [x] カードの詳細を閲覧できる 🔴 
  - [x] カードの削除ができる
- カード編集画面
  - [x] カードの編集ができる

**Comment by niwatolli3** [comment]
もくもくマン
